### ISSUE TITLE
Icons not displayed in VisualStudio

### ISSUE THREAD

**Issue by KaeptnHelmut** [awesome-inc/FontAwesome.Sharp#22] opened 2019-06-21 12:41 UTC
In WPF designer i do not see the Icons. In the compiled program however they are displayed

**Comment by mkoertgen** [comment] 2019-06-21 14:20
Hi @KaeptnHelmut, thanks for reporting the issue. 

This seems to be a duplicate of https://github.com/awesome-inc/FontAwesome.Sharp/issues/3 which we closed back then.

If this is bugging you give a quick reply that this should be fixed or better yet, submit a PR.

**Comment by mkoertgen** [comment] 2019-09-11 06:27
Closed after inactivity

**Closed as completed by mkoertgen** 2019-09-11 06:27 UTC

**Comment by Incisive** [comment] 2020-07-12 13:23
Hi @mkoertgen I'm experiencing the same issues.  To reproduce:

- Create a brand new WPF C# Project
- Install Nuget package for FontAwesome.Sharp
- Add necessary xmlns for FontAwesome
- Add the following button the the default grid: `<fa:IconBlock Icon="Info" Foreground="Chocolate"/>`
- Square visible in designer instead of Info button.

This isn't a huge issue as it's visible in the built application, but I'm curious if there is any known fix for this or a way to have them show up in the designer too?

Thanks

**Comment by mkoertgen** [comment] 2020-07-12 13:54
Hi @Incisive ,

We did not track this one down exactly but suggested some pathways to go down in https://github.com/awesome-inc/FontAwesome.Sharp/issues/3#issuecomment-248824813

If you have some time to spare we would love to accept a PR on this.
