### ISSUE TITLE
Button content not properly aligned.

### ISSUE THREAD

**Issue by Sensei6x9** [awesome-inc/FontAwesome.Sharp#98] opened 2022-08-11 00:50 UTC
**Describe the bug**
In VB.Net WinForms; Button content is not properly aligned in middle. The icon is leaning towards the top even when alignment is set to center.

**To Reproduce**
Set the button's property to this
![image](https://user-images.githubusercontent.com/96456175/184046900-3cca6a94-b66c-46d1-928b-d56a2f1ea2a4.png)

**Comment by mkoertgen** [comment] 2022-08-11 09:31
Reproducing in VS2022 / net6 using the latest package

Without any icon it looks properly aligned
![image](https://user-images.githubusercontent.com/7235760/184103408-ca22c544-ab91-4fcd-9047-1b79e502a349.png)

Setting an icon
![image](https://user-images.githubusercontent.com/7235760/184103609-99236a34-16b8-47f4-b1a3-bd6e47ea6a84.png)

Now setting alignment properties
ImageBeforeText
![image](https://user-images.githubusercontent.com/7235760/184104059-0e4de3f0-fcfc-4d7b-b976-8cbe21026070.png)

TextBeforeImage
![image](https://user-images.githubusercontent.com/7235760/184104089-1fe13cc7-2287-465f-8a87-26d3f7e4b212.png)

**Comment by mkoertgen** [comment] 2022-08-11 09:32
Now I checked with a standard button (screenshotted the icon, and loaded it to the button). Spoiler: Exact the same behaviour

![image](https://user-images.githubusercontent.com/7235760/184104826-08d0dc7b-f97d-4743-a796-7b86cfcc28ae.png)

**Comment by mkoertgen** [comment] 2022-08-11 09:32
Closing this as "won't fix" if it's ok for you @Sensei6x9

**Closed as completed by mkoertgen** 2022-08-11 09:32 UTC
Labels: wontfix

**Comment by Sensei6x9** [comment] 2022-08-14 15:00
Sorry @mkoertgen, forgot to visit this issue. Yeah, it's okay, I see now that there is a somewhat minimum button height needed to make it look at least like it's properly aligned.

As always, thank you for a prompt reply.

**Comment by emccourt** [comment] 2023-12-13 17:22
Hi, I'm visiting this issue now, as I'm having the same problems with vertical alignment. The icon is significantly closer to the top of the IconButton, even with a small icon compared to a large container. 

Here is an example, icon size 48 in a button size 100x100 with no padding (screenshotted then measured in Paint3D to show difference):
<img src="https://github.com/awesome-inc/FontAwesome.Sharp/assets/25906998/34dddce5-5917-4356-86a4-56eebbee9cbb" width="250" height="250">
<img src="https://github.com/awesome-inc/FontAwesome.Sharp/assets/25906998/fd9a6c6c-047b-42a2-9771-b07e2813e8bc" width="250" height="250">


I'm also confused by your reply of "the standard Button has the same behavior" @mkoertgen - in the screenshots you posted, the standard Button seems to be vertically centering the icon correctly (text is between the two horizontal lines of the icon), whereas the IconButton is clearly shifted upwards (text now aligns with the bottom horizontal line of the icon)

**Comment by mkoertgen** [comment] 2023-12-15 18:31
Hi @emccourt ,

Hm, not sure if I recall correctly. But, yes, now that you are bringing it up again, I see that there is a clear vertical alignment shift between the Button and IconButton screenshots.

Feel free to reopen the issue. Not sure whether I can help much with remediation in the near future.
