### ISSUE TITLE
For .Net Core

### ISSUE THREAD

**Issue by cempol** [awesome-inc/FontAwesome.Sharp#30] opened 2020-01-23 19:42 UTC
Is it too early to ask if  we can use it for windows form .Net Core..?

**Comment by mkoertgen** [comment] 2020-01-23 22:46
@cemalpolat The timing is about right in case you are not in too much of a hurry. 
I am just in the middle of migrating the build to netcore3.1 on branch [netcore](https://github.com/awesome-inc/FontAwesome.Sharp/tree/netcore).

Here is the current state of the [TestForms](https://github.com/awesome-inc/FontAwesome.Sharp/blob/netcore/TestForms/TestForms.csproj)-app.

Feel free to help out checking `netcoreapp3.1` as a target framework.

**Comment by mkoertgen** [comment] 2020-01-23 23:18
Well, only netcore3.0 supported but that seems to work just fine, cf.:

- https://ci.appveyor.com/project/awesome-inc-build/fontawesome-sharp

**Comment by mkoertgen** [comment] 2020-01-25 16:43
Duplicate of #29

**Closed as completed by mkoertgen** 2020-01-25 16:43 UTC
