### ISSUE TITLE
TestWpf doesn´t run

### ISSUE THREAD

**Issue by moramatte** [awesome-inc/FontAwesome.Sharp#82] opened 2021-11-29 08:23 UTC
The TestWpf application crashes immediately. (TestForms works).

**To Reproduce**
1. Clone the repo
2. Set TestWpf as startup project
3. Press F5 to debug the application
4. See error: Crash (Value cannot be null. (Parameter 'fontFamily')') .. on row 26 in IconBlockBase.cs

**Expected behavior**
No crash - normal start

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by mkoertgen** [comment] 2021-11-29 09:00
Hi @moramatte ,

After a clean build I could reproduce it. The TestWPF contains a tab for testing the pro-fonts which are not available on a fresh clone. I will remove the pro-tab on the main branch.

**Comment by mkoertgen** [comment] 2021-11-29 10:21
Removed the pro-examples on the main branch. Should be fixed.

**Closed as completed** 2021-11-29 10:21 UTC

**Comment by moramatte** [comment] 2021-11-29 10:36
Thanks.
A control question: We are looking for a component that will allow us to use multicolor icon fonts with custom made icons.
Do you think your component will do the trick, if I follow the steps under "Custom fonts"?
Is css required, or can we do simply with a otf font?
Regards, Moramatte

**Comment by mkoertgen** [comment] 2021-11-29 12:20
Hi @moramatte ,

I don't think glyph-font-approaches are a good fit for multi-color icons because it's based on, well, fonts.
There are probably some theoretical workarounds using stacked icons or something like that.
But I guess going down this road, you will lose the main pros of using a font, e.g. not having to care a fair bit about crafting your icons.
